from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
WAV_OUTPUT_DIR = OUTPUTS_DIR / "wav"
MP3_OUTPUT_DIR = OUTPUTS_DIR / "mp3"
INPUT_AUDIO_DIR = PROJECT_ROOT / "input_audio"

DEFAULT_MODEL_NAME = "facebook/musicgen-small"
DEFAULT_DURATION_SECONDS = 10
DEFAULT_SAMPLE_RATE = 32000
DEFAULT_DEVICE = "cuda"
DEFAULT_OUTPUT_FORMAT = "wav"
DEFAULT_OUTPUT_FILENAME_PREFIX = "musicgen_output"

SUPPORTED_OUTPUT_FORMATS = ["wav"]
SUPPORTED_DEVICES = ["cuda", "cpu"]

HF_CACHE_DIR = PROJECT_ROOT / "hf_cache"
REQUIRED_DIRECTORIES = [WAV_OUTPUT_DIR, MP3_OUTPUT_DIR, INPUT_AUDIO_DIR, HF_CACHE_DIR]